- name: Install OpenVPN con retry (lock apt workaround)
  become: true
  apt:
    name: openvpn
    state: present
    update_cache: yes
  register: result_apt
  until: result_apt is succeeded
  retries: 5
  delay: 15

- name: Debug VAULT_TOKEN sul nodo target
  debug:
    msg: "Token sul nodo target: {{ VAULT_TOKEN | default('non definito') }}"


- name: Recupera openvpn_config in modo statico
  set_fact:
    openvpn_config: >-
      {{ lookup('hashi_vault',
                'secret=secret/vpnbox-nbs field=openvpn_config',
                token='{{ VAULT_TOKEN }}',
                url='http://vault:8200') }}

- name: Scrivi file /etc/openvpn/client-{{ vpn_id }}.conf
  become: true
  copy:
    dest: "/etc/openvpn/client-{{ vpn_id }}.conf"
    content: "{{ openvpn_config }}"
    mode: '0600'



