- name: Install OpenVPN con retry (lock apt workaround)
  become: true
  apt:
    name: openvpn
    state: present
    update_cache: yes
  register: result_apt
  until: result_apt is succeeded
  retries: 5
  delay: 15

- name: Debug VAULT_TOKEN sul nodo target
  debug:
    msg: "Token sul nodo target: {{ VAULT_TOKEN | default('non definito') }}"

- name: Recupera configurazione da Vault per {{ vpn_id }}
  set_fact:
    openvpn_config: >-
      {{ lookup('hashi_vault',
                'secret=secret/vpnbox-' ~ vpn_id ~ ' field=openvpn_config',
                token=hostvars['localhost']['VAULT_TOKEN'],
                url=lookup('env', 'VAULT_ADDR')) }}

- name: Scrivi file /etc/openvpn/client-{{ vpn_id }}.conf
  become: true
  copy:
    dest: "/etc/openvpn/client-{{ vpn_id }}.conf"
    content: "{{ openvpn_config }}"
    mode: '0600'



