- name: Install OpenVPN con retry (lock apt workaround)
  become: true
  apt:
    name: openvpn
    state: present
    update_cache: yes
  register: result_apt
  until: result_apt is succeeded
  retries: 3
  delay: 5

- name: Debug VAULT_TOKEN sul nodo target
  debug:
    msg: "Token sul nodo target: {{ VAULT_TOKEN | default('non definito') }}"


- name: Recupera segreto da Vault KV2 usando il modulo
  community.hashi_vault.vault_kv2_get:
    url: http://vault:8200
    token: "{{ VAULT_TOKEN }}"
    path: secret/vpnbox-nbs
    field: openvpn_config
  register: vpn_secret_result


- name: Utilizza il segreto
  debug:
    msg: "La configurazione OpenVPN è: {{ vpn_secret_result.value }}"

- name: Scrivi file /etc/openvpn/client-{{ vpn_id }}.conf
  become: true
  copy:
    dest: "/etc/openvpn/client-{{ vpn_id }}.conf"
    content: "{{ vpn_secret_result.value }}"
    mode: '0600'



