- name: Install OpenVPN con retry (lock apt workaround)
  become: true
  apt:
    name: openvpn
    state: present
    update_cache: yes
  register: result_apt
  until: result_apt is succeeded
  retries: 3
  delay: 5

- name: Debug VAULT_TOKEN sul nodo target
  debug:
    msg: "Token sul nodo target: {{ VAULT_TOKEN | default('non definito') }}"


- name: Imposta la variabile openvpn_config recuperandola da Vault
  ansible.builtin.set_fact:
        openvpn_config: >-
          {{ lookup('hashi_vault',
                    'secret=secret/data/vpnbox-nbs field=openvpn_config',
                     token=lookup('env', 'VAULT_TOKEN'),
                     url=lookup('env', 'VAULT_ADDR')) }}


- name: Estrai openvpn_config dal segreto
  set_fact:
    openvpn_config: "{{ openvpn_config }}"

- name: Scrivi file /etc/openvpn/client-nbs.conf
  become: true
  copy:
    dest: "/etc/openvpn/client-nbs.conf"
    content: "{{ openvpn_config }}"
    mode: '0600'


