- name: Install OpenVPN con retry (lock apt workaround)
  become: true
  apt:
    name: openvpn
    state: present
    update_cache: yes
  register: result_apt
  until: result_apt is succeeded
  retries: 3
  delay: 5

- name: Debug VAULT_TOKEN sul nodo target
  debug:
    msg: "Token sul nodo target: {{ VAULT_TOKEN | default('non definito') }}"


- name: Recupera configurazione OpenVPN da Vault
  community.hashi_vault.vault_kv2_get:
    url: "{{ lookup('env', 'VAULT_ADDR') }}"
    token: "{{ lookup('env', 'VAULT_TEST_TOKEN') }}"
    engine_mount_point: "secret"     # <== nome del mount, di default è 'secret'
    path: "vpnbox-{{ vpn_id }}"      # <== solo la chiave, NON includere 'data/'
  register: vault_response
  delegate_to: localhost
  become: false

- name: Debug vault_response
  debug:
    var: vault_response.data.data.openvpn_config

# - name: Estrai configurazione OpenVPN
#   set_fact:
#      openvpn_config: "{{ vault_response.data}}"

# -  name: Scrivi configurazione OpenVPN
#    copy:
#     dest: "/etc/openvpn/client-{{ vpn_id }}.conf"
#     content: "{{ openvpn_config }}"
#     mode: '0600'