- name: Setup OpenVPN Clients da Vault
  hosts: all
  become: true
  become_user: root
  vars:
    vpn_ids: ["nbs", "tredipi"]  # Sovrascrivibile via -e vpn_ids=[...]



  pre_tasks:
    - name: Login a Vault via AppRole
      uri:
        url: "{{ VAULT_ADDR }}/v1/auth/approle/login"
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
        body:
          role_id: "{{ VAULT_ROLE_ID }}"
          secret_id: "{{ VAULT_SECRET_ID }}"
        return_content: yes
      register: vault_login
      delegate_to: localhost

    - name: Set VAULT_TOKEN
      set_fact:
        VAULT_TOKEN: "{{ vault_login.json.auth.client_token }}"
  tasks:

    - name: Verifica privilegi sudo
      command: whoami
      register: whoami_output

    
    - name: Recupera configurazioni VPN da Vault e installa OpenVPN
      include_tasks: configure_openvpn.yml
      loop: "{{ vpn_ids }}"
      loop_control:
        loop_var: vpn_id

