- name: Setup OpenVPN Clients da Vault
  hosts: all
  become: true
  become_user: root
  vars:
    vpn_ids: ["nbs", "tredipi"]  # Sovrascrivibile via -e vpn_ids=[...]

  tasks:

    - name: Verifica privilegi sudo
      command: whoami
      register: whoami_output

    
    - name: Recupera configurazioni VPN da Vault e installa OpenVPN
      include_tasks: configure_openvpn.yml
      loop: "{{ vpn_ids }}"
      loop_control:
        loop_var: vpn_id

