- name: Setup OpenVPN Clients da Vault
  hosts: all
  become: true
  vars:
    vpn_ids: []

  tasks:

    - name: Debug lista VPN da configurare
      debug:
	var: vpn_ids

    - name: Recupera configurazioni VPN da Vault e installa OpenVPN
      include_tasks: configure_openvpn.yml
      loop: "{{ vpn_ids }}"
      loop_control:
        loop_var: vpn_id
